### ISSUE TITLE
caQtDM needs to run apsbss from a button

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/caQtDM-screens#4]
@jilavsky emailed:

> How do the buttons run the [apsbss] scripts? And what they are? I see the screen points to the file as apsbss, but I cannot find it.
> 
> Simply put, even after reading this page : https://apstools.readthedocs.io/en/latest/applications/apsbss.html#displays-for-medm-caqtdm

**Comment by prjemian** [comment]
Probably the [apsbss] documentation has assumed something it did not state.  The button calls a python program and that program is available on the default path in the caQtDM session.  If caQtDM is started without apsbss available on the PATH, the buttons will fail.

**Comment by prjemian** [comment]
It may be easiest to place the `~usaxs/bin` directory on the PATH inside the shell script that starts caQtDM.  Then, the buttons will find this shell script `~usaxs/bin/apsbss` that sets up and launches `apsbss` from the proper python.

Here is the content of that script:

```
#!/bin/bash

export BLUESKY_ROOT=/APSshare/anaconda3/Bluesky

source ${BLUESKY_ROOT}/bin/activate base
apsbss $@
```

**Comment by prjemian** [comment]
I just created `/APSshare/bin/apsbss` from this script.  The caQtDM starter script used by USAXS (`/net/s9dserv/xorApps/epics/screens/usaxs/start_caQtDM_usaxs.sh`) has this line:

```
export PATH=${PATH}:/APSshare/bin
```

Once the `/APSshare/bin/apsbss` script is pushed out to the s8dserv (tomorrow morning), the buttons *should* start working since `apsbss` will be found on the `PATH`.  @jilavsky : comment here tomorrow whether or not the buttons work for you then.

**Comment by prjemian** [comment]
If it works, close this issue.

**Comment by jilavsky** [comment]
Something caused this to start working now. 
which apsbss shows ~/bin/apsbss 
I run the scripts manually and tested they work. SInce then they work also from buttons. Take 5 seconds run, but they work now. 
not sure how this got sorted out, may be Kevin fixed it?

**Comment by prjemian** [comment]
Maybe restarted caQtDM since I added `~usaxs/bin/apsbss` a week ago or so.
